from enum import StrEnum


class AuditAction(StrEnum):
    """集中维护所有审计日志的操作类型，方便引用和检索。"""

    # 认证相关
    AUTH_LOGIN = "AUTH_LOGIN"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_REFRESH = "AUTH_REFRESH"
    AUTH_LOGOUT = "AUTH_LOGOUT"

    # 角色 / 权限管理
    ROLE_PERMISSION_CREATE = "ROLE_PERMISSION_CREATE"
    ROLE_PERMISSION_UPDATE = "ROLE_PERMISSION_UPDATE"
    ROLE_PERMISSION_DELETE = "ROLE_PERMISSION_DELETE"

    # 用户管理
    USER_DELETE = "USER_DELETE"
    ADMIN_CREATE_USER = "ADMIN_CREATE_USER"
    USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE"
    USER_PASSWORD_UPDATE = "USER_PASSWORD_UPDATE"

    # 系统异常
    HTTP_EXCEPTION = "HTTP_EXCEPTION"
    UNHANDLED_EXCEPTION = "UNHANDLED_EXCEPTION"
